alias as="aliaser show"
alias l='ls -la'
alias addpath='export PATH=$PATH:$PWD/build'
alias c='clear'
alias octave='octave-3.8.0'
alias maxeler="ssh smasuti@des-maxeler01.spms.ntu.edu.sg"
alias addnvcc='export PATH=$PATH:/usr/local/cuda/bin'
alias kip="echo 155.69.57.65"
alias ipp="echo 155.69.144.19"
alias read="vi ~/src/mybashrc/readmedir/readme.txt"
alias tac='tail -r'
alias clone="git clone git@git.assembla.com:relax_cuda.git"
alias drop="cd /Users/smasuti/Documents/EOS/dropbox"
alias e="exit"
alias ep="echo $PATH"
alias esclass=" cd ~/Documents/EOS/dropbox/es7008/"
alias h="cd ~"
alias komodo="ssh -Y sagarshr001@155.69.57.65"
alias miracle="ssh -Y smasuti@10.27.198.63"
alias krakatoa=" ssh sbarbot@krakatoa.staff.main.ntu.edu.sg"
alias ma="module avail"
alias mfink="module load fink"
alias ml="module list"
alias mol="module load"
alias mul="module unload"
alias mp="module purge"
alias nvid="cd /Developer/NVIDIA/CUDA-5.5/samples/mine/"
alias pdcc="ssh -Y smasuti@155.69.144.19"
alias rc="vi ~/.bashrc"
alias s="source ~/.bashrc"
alias scrooge="ssh sagarshr001@scrooge.sce.ntu.edu.sg"
alias ufink="module unload fink"
alias al="vi ~/.aliases.sh"
alias nya2="ssh -Y smasuti@nya2.hpc.ntu.edu.sg"
alias insar="cd ~/src/insar"
alias q="showq"
alias can="canceljob "
alias gp="git push"
alias gl="git pull"
alias gc="git commit -a"
alias diff="diff -u"
alias gnu="vi ~/src/mybashrc/readmedir/gnuplot.txt"
alias check="vi ~/src/tasks"
alias may="vi ~/Documents/EOS/dropbox/docs/sagar/expenses/may15.txt"
alias mechanics="ssh -Y mechanics@komodo.spms.ntu.edu.sg"
alias qm="qstat -f "
alias lat="vi ~/src/mybashrc/readmedir/latex.txt"
alias todo="vi ~/Documents/EOS/dropbox/geophysics/preparation/list.txt"
alias wpap="vi ~/src/paper/wharton12/masuti+16.tex"

function pral() {
echo "as -> aliaser show"
echo "l -> ls -la"
echo "addpath -> export PATH=PATH:PWD/build"
echo "c -> clear"
echo "octave -> octave-3.8.0"
echo "maxeler -> ssh smasuti@des-maxeler01.spms.ntu.edu.sg"
echo "addnvcc -> export PATH=PATH:/usr/local/cuda/bin"
echo "kip -> echo 155.69.57.65"
echo "ipp -> echo 155.69.144.19"
echo "read -> vi ~/src/mybashrc/readmedir/readme.txt"
echo "tac -> tail -r"
echo "clone -> git clone git@git.assembla.com:relax_cuda.git"
echo "drop -> cd /Users/smasuti/Documents/EOS/dropbox"
echo "e -> exit"
echo "ep -> echo PATH"
echo "esclass ->  cd ~/Documents/EOS/dropbox/es7008/"
echo "h -> cd ~"
echo "miracle -> ssh -Y smasuti@10.27.198.63"
echo "komodo -> ssh -Y sagarshr001@155.69.57.65"
echo "krakatoa ->  ssh sbarbot@krakatoa.staff.main.ntu.edu.sg"
echo "ma -> module avail"
echo "matlab -> matlab -nojvm -nodisplay -nosplash"
echo "mfink -> module load fink"
echo "ml -> module list"
echo "mol -> module load"
echo "mul -> module unload"
echo "nvid -> cd /Developer/NVIDIA/CUDA-5.5/samples/mine/"
echo "pdcc -> ssh -Y smasuti@155.69.144.19"
echo "rc -> vi ~/.bashrc"
echo "s -> source ~/.bashrc"
echo "scrooge -> ssh smasuti@scrooge.sce.ntu.edu.sg"
echo "ufink -> module unload fink"
echo "al -> vi ~/.aliases.sh"
echo "nya2 -> ssh -Y smasuti@nya2.hpc.ntu.edu.sg"
echo "insar -> cd ~/src/insar"
echo "q -> qstat"
echo "can -> canceljob "
echo "gp -> git push"
echo "gl -> git pull"
echo "gc -> git commit -a"
echo "diff -> diff -u"
echo "gnu -> vi ~/src/mybashrc/readmedir/gnuplot.txt"
echo "mp -> module purge"
echo "check -> vi ~/src/tasks"
echo "may -> vi ~/Documents/EOS/dropbox/docs/sagar/expenses/may15.txt"
echo "mechanics -> ssh -Y mechanics@komodo.spms.ntu.edu.sg"
echo "qm -> qstat -f "
echo "lat -> vi ~/src/mybashrc/readmedir/latex.txt"
echo "todo -> vi ~/Documents/EOS/dropbox/geophysics/preparation/list.txt"
echo "wpap -> vi ~/src/paper/wharton12/masuti+16.tex"
}
